{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "foodapp.serviceAccountName" . }}
  labels:
{{ include "foodapp.labels" . | indent 4 }}
{{- end -}}
