version: "3"
services:
  app:
    container_name: foodapp
    command: nodemon -L index.js
    # restart: always
    build: ./
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    links:
      - mongo
    env_file:
      - ./config/dev.env
  mongo:
    container_name: foodapp-mongo
    image: mongo
    ports:
      - "27017:27017"